version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - CHAT_API_KEY=${CHAT_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED}
    depends_on:
      - mongo
  ui:
    build: ./ui
    ports:
      - "3030:5173"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL}

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
