name: Build and Publish Docker Images (api & ui)

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push api image
      run: |
        docker build -t francobpan/ai-snippet-api:${{ github.sha }} ./api
        docker push francobpan/ai-snippet-api:${{ github.sha }}

    - name: Build and push ui image
      run: |
        docker build -t francobpan/ai-snippet-ui:${{ github.sha }} ./ui
        docker push francobpan/ai-snippet-ui:${{ github.sha }}

    - name: Tag and push latest images
      run: |
        docker tag francobpan/ai-snippet-api:${{ github.sha }} francobpan/ai-snippet-api:latest
        docker push francobpan/ai-snippet-api:latest

        docker tag francobpan/ai-snippet-ui:${{ github.sha }} francobpan/ai-snippet-ui:latest
        docker push francobpan/ai-snippet-ui:latest
